#pragma config(Sensor, dgtl1,  quadEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, light,          sensorNone)
#pragma config(Motor,  port2,           shootMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           intakeMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//**********************************************************************************//

// Seting up some variables
int speedRM;
int speedLM;
int speedCham = 127;
int speedArm = 100;
int off = 0;
int maxAngleArm = 90;

//*********************************************************************************//

// Movement functions

// For moving forwards or back
void mStraight(int s, int t)
{
	// Moves the motors forward
	// Given a 's' for speed: positve forwards, negative backwards
	// Given a 't' for time in miliseconds
	motor[rightMotor] = s;
	motor[leftMotor] = s;
	wait1Msec(t);
	motor[rightMotor] = off;
	motor[leftMotor] = off;
}

void mTurn(int d, int angle)
{
	// Center turns the robot
	// Given a 'd' for direction: 1 for right, and -1 for left
	// Given a 'r' for rotations: r = 4 is a full turn
	motor[rightMotor] = -67 * d;
	motor[leftMotor] = 67 * d;
	wait1Msec(angle);
	motor[rightMotor] = off;
	motor[leftMotor] = off;
}

void mArmUp()
{
	// Moves the arm up
	motor[armMotor] = speedArm;
	wait1Msec(1000);
	motor[armMotor] = off;
}

void mShoot(int t)
{
	// Controls the intake and shooter
	// Given a 't' for time in miliseconds
	motor[intakeMotor] = speedCham;
	motor[shootMotor] = speedCham;
	wait1Msec(t);
	motor[intakeMotor] = off;
	motor[shootMotor] = off;
}

// This will flash the led
void flash()
{
	for (int i = 0; i < 3; i = i + 1)
	{
		turnLEDOn(light);
		wait1Msec(100);
		turnLEDOff(light);
		wait1Msec(100);
	}
}
//********************************************************************************//

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// Flashes to signify starting a new mode
	flash();

	mStraight(67, 200);
	mTurn(-1, 750);
	mStraight(67, 2500);
	mStraight(-67, 800);
	mTurn(1, 850);

	mStraight(67, 1000);
	mTurn(-1, 750);
	mStraight(67, 800);
	mStraight(-67, 800);
	mTurn(1, 850);

	mStraight(67, 1000);
	mTurn(-1, 750);
	mStraight(67, 800);
	mStraight(-67, 800);
	mTurn(1, 850);



	// ..........................................................................
	// Insert user code here ^^^
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	// Flashes to signify starting a new mode
	flash();

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// Gets the speed values for both right and left motors by Ch3
		speedRM = vexRT[Ch3];
		speedLM = vexRT[Ch3];

		// Calculates turning left and right with Ch4 values
		speedRM = speedRM + vexRT[Ch4];
		speedLM = speedLM - vexRT[Ch4];

		// Sets the final speeds to both motors
		motor[rightMotor] = speedLM;
		motor[leftMotor] = speedRM;

		// If Btn6U is pressed/holding down
		// This is how all the other ifs are coded
		if (vexRT[Btn6U] == 1)
		{
			// The "Chamber" (intake and shoot) motors will run a speedCham
			motor[intakeMotor] = speedCham;
			motor[shootMotor] = speedCham;
		}
		else if (vexRT[Btn6D] == 1)
		{
			// The Chamber will go in verse
			motor[intakeMotor] = speedCham * -1;
			motor[shootMotor] = speedCham * -1;
		}
		else if (vexRT[Btn5U] == 1)
		{
			// This lifts the arm up

			// If the arm has not moved above its maximum angle
			if (SensorValue[quadEncoder] < maxAngleArm)
			{
				// Arm up
				motor[armMotor] = speedArm;
			}
			else
			{
				// Arm has reached its max angle
				// So it cuts the power to it
				motor[armMotor] = off;
			}
		}
		else if (vexRT[Btn5D] == 1)
		{
			// This lifts the arm down
			motor[armMotor] = speedArm * -1;
		}
		else if (vexRT[Btn7L] == 1 && vexRT[Btn8R] == 1)
		{
			// This will exit back to main task
			// And also start the autonomous period
		}
		else
		{
			// Turns the motors off
			motor[intakeMotor] = off;
			motor[shootMotor] = off;
			motor[armMotor] = off;
		}

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc ^^^
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
